### ISSUE TITLE
Site UX & Search Algorithm

### ISSUE THREAD

**Issue by jyash97** [feathericons/feathericons.com#216]
Hey Guys!

Great work on the project 💯. I use the lib for every project of mine. 

I have minor feedback - Can we have the search input sticky as the user scrolls down he can see the search bar. Check this screenshot:
![image](https://user-images.githubusercontent.com/22376783/55216305-5cc08f80-5222-11e9-9a2c-3efb017a7aff.png)

Also if I search with keyword `ey` I get 5 results and if I search with `eye` keyword it return more than 10 results. 

Do let me know if this sounds good I am happy to contribute to the project.

Thanks

**Comment by colebemis** [comment]
The search input is now sticky and I tweaked the search options a bit 👍 I’m going to go ahead and close this issue but feel free to open another one if you’re still noticing problems.
