### ISSUE TITLE
Focusable search shortcut issue in FireFox

### ISSUE THREAD

**Issue by adarsh4d** [feathericons/feathericons.com#278]
### Browser
Firefox

### What is expected?
Using `/` shortcut to focus the search.

### What is actually happening?
Triggers the quick find option

### Possible solution
* Using MouseTrap (https://github.com/ccampbell/mousetrap/) to capture the key press event.
* Change to another key which is not used by browser

**Comment by colebemis** [comment]
What version of Firefox are you using? `/` works for me when I tried it in Firefox. Do you have any extensions installed that might be causing this issue?

**Comment by adarsh4d** [comment]
The issue is now resolved,

**Comment by adarsh4d** [comment]
Thank you for the awesome project. I took a lot of inspiration from your website and built this, https://svg-logo.netlify.com/
