### ISSUE TITLE
Dark mode 🌚

### ISSUE THREAD

**Issue by colebemis** [feathericons/feathericons.com#285]

**Comment by johnletey** [comment]
@colebemis What do you think about using [Theme UI](https://theme-ui.com)?

I'll see if I can get a working demo up real quick

**Comment by colebemis** [comment]
@johnletey Great minds think alike 😄 https://github.com/feathericons/feathericons.com/pull/286

**Comment by colebemis** [comment]
Here's the deploy preview: https://5dc3e9a82f689d000cffc8ab--feather.netlify.com/

**Comment by colebemis** [comment]
Closed by #286
